services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./bin/dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: guitar_practice_app_development

volumes:
  postgres_data:
